### ISSUE TITLE
Time is NaN when reading from log file

### ISSUE THREAD

**Issue by bradleygore** [kvegter/query-analyzer-app#3] opened 2020-09-23 16:43 UTC
I've a locally running neo4j instance, and when analyzing the in-memory query logs the data is fully populated. However, when reading the log files written out by that same neo4j instance, all of the Time fields are `NaN`.

Neo4j Version: 4.1.1 Enterprise
Neo4j Query Log Analyzer version 1.0.1

**Query Stats**
<img width="1600" alt="Screen Shot 2020-09-23 at 11 38 00 AM" src="https://user-images.githubusercontent.com/5077928/94043027-e575a880-fd91-11ea-912f-59e819a0c194.png">
**Query Log**
<img width="1534" alt="Screen Shot 2020-09-23 at 11 38 12 AM" src="https://user-images.githubusercontent.com/5077928/94043084-f9b9a580-fd91-11ea-953d-006ad7b3b346.png">

**Comment by kvegter** [comment] 2020-10-06 15:25
I think this is caused by small changes in the query log record layout in 4.1. This is fixed in 1.0.2

**Closed** 2020-12-18 12:12 UTC
